language: c

compiler: gcc

before_script:
    - mkdir build/
    - cd build/
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../output/

script:
    - make -j4
    - make install

after_script:
    - ./test/mempool_test

notifications:
    email:
        - jianfan.tw@gmail.com
    on_success: change
    on_failure: always
